version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - lavalink

  lavalink:
    image: fredboat/lavalink:4
    hostname: lavalink
    restart: unless-stopped
    volumes:
      - ./config/application.yml:/opt/Lavalink/application.yml:ro
